### ISSUE TITLE
Sign In Failed: TimeoutError: Timeout awaiting 'request' for 2500ms

### ISSUE THREAD

**Issue by SamuelBradley** [magda-io/magda-auth-oidc#1]
Getting error when attempting to login using an OIDC connection. 
`Sign In Failed: TimeoutError: Timeout awaiting 'request' for 2500ms`

Happens consistently on the first login attempt and usually works on the second attempt, with an OIDC connection to AWS Cognito. Doing some searching around the internets It may be linked to a default value in an OIDC middleware library. (https://devforum.okta.com/t/timeouterror-timeout-awaiting-request-for-2500ms/9878/5) Is the only related post on this issue I could find.

I've tried setting the timeout value for this plugin, but the default value of 10000ms already far exceeds the value cause an error.

**Comment by SamuelBradley** [comment]
We are using version 1.1.0 of the plugin

`  - name: magda-auth-oidc
    version: 1.1.0
    repository: https://charts.magda.io
    tags:
      - all
      - magda-auth-oidc`

**Comment by t83714** [comment]
AWS cognito is not a standard OIDC implementation --- its implementation seems have some bug with URL encoding and incorrectly generate "nonce" when federate Active Directory.
We internally have a customised version to accommodate those issues --- I might release it sometime in future after make it more generic (it won't be in short term)
For your error, I suspect it's a different issue.

Have you add the OIDC issuer in your Magda config? Could you please provide your config?

**Comment by SamuelBradley** [comment]
```yaml
# Cognito OIDC config
# Note: `issuer` & `clientId` are supplied through the `magda-oidc-config` secret
magda-auth-oidc:
      authPluginConfig:
        name: "XT Users"
      issuerName: "xt-dev-cognito-oidc"
      scope: "openid email"
      timeout: 10000
```
